import { defineConfig } from 'vite'
import solid from 'vite-plugin-solid'
import { viteSingleFile } from "vite-plugin-singlefile"
import htmlMinimize from '@sergeymakinen/vite-plugin-html-minimize'
import viteCompression from 'vite-plugin-compression';
import { name, version } from "./package.json"

export default defineConfig({
  plugins: [
    solid(),
    viteCompression({ algorithm: "gzip" }),
    {
      name: 'rename',
      enforce: 'post',
      generateBundle(_, bundle) {
        bundle['index.html'].fileName = `${name}.${version}.html`;
      },
    },
    viteSingleFile(),
    htmlMinimize({
      minifierOptions: {
        collapseWhitespace: true,
        collapseInlineTagWhitespace: true,
        html5: true,
        keepClosingSlash: false,
        minifyCSS: false,
        minifyJS: false,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeOptionalTags: true,
        includeAutoGeneratedTags: false,
      }
    }),
  ],
  build: {
    target: "esnext",
    modulePreload: {
      polyfill: false
    },
    reportCompressedSize: false,
    chunkSizeWarningLimit: Infinity,
  }
})
